# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-22 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Используйте "index" для главной страницы', max_length=15, verbose_name='Ссылка')),
                ('content', models.TextField(help_text='HTML', verbose_name='Содержимое страницы в формате HTML')),
            ],
            options={
                'verbose_name_plural': 'Страницы',
                'verbose_name': 'Страница',
            },
        ),
    ]
