# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-22 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dual_job_holder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='menu_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('link', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='menu_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='professors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150)),
                ('standing', models.CharField(max_length=150)),
                ('seniority', models.CharField(max_length=150)),
                ('categoty', models.CharField(max_length=150)),
                ('dateofcategory', models.DateField(null=True)),
                ('education', models.CharField(max_length=150)),
                ('colledge', models.CharField(max_length=2500)),
                ('isdualjobholder', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='professors2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150)),
                ('standing', models.CharField(max_length=150)),
                ('education', models.CharField(max_length=150)),
                ('categoty', models.CharField(max_length=150)),
                ('dateofcategory', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='menu_item',
            name='caption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.menu_main'),
        ),
    ]
