# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-22 12:41
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_item',
            name='link',
        ),
        migrations.AddField(
            model_name='menu_item',
            name='document',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Документ'),
        ),
    ]
