# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-22 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu_item',
            options={'verbose_name': 'Элемент меню', 'verbose_name_plural': 'Элементы меню'},
        ),
        migrations.AlterModelOptions(
            name='menu_main',
            options={'verbose_name': 'Название пункта', 'verbose_name_plural': 'Названия пунктов'},
        ),
    ]
