# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-22 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('answer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=30)),
                ('isdeleted', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='clientsanswers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('datetime', models.DateTimeField(auto_now=True, null=True)),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blankform.answer')),
            ],
        ),
        migrations.CreateModel(
            name='clientsession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('clientsession', models.CharField(max_length=90)),
                ('customcomment', models.CharField(max_length=1024, null=True)),
                ('datetime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=512)),
                ('isdeleted', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='clientsanswers',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blankform.clientsession'),
        ),
        migrations.AddField(
            model_name='clientsanswers',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blankform.question'),
        ),
    ]
