# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-22 12:09
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu_item',
            options={'verbose_name': 'Элемент меню', 'verbose_name_plural': 'Элементы меню'},
        ),
        migrations.AlterModelOptions(
            name='menu_main',
            options={'verbose_name': 'Название пункта', 'verbose_name_plural': 'Названия пунктов'},
        ),
        migrations.AddField(
            model_name='menu_item',
            name='document',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='PDF'),
        ),
    ]
